# Generated by Django 6.0.3 on 2026-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength Training'), ('flexibility', 'Flexibility'), ('functional', 'Functional Training'), ('recovery', 'Recovery')], max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('specifications', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('cardio', 'Cardio Zone'), ('weights', 'Weight Training'), ('functional', 'Functional Area'), ('yoga', 'Yoga & Stretching'), ('locker', 'Locker Room'), ('pool', 'Pool Area'), ('studio', 'Studio')], max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='facilities/')),
                ('capacity', models.PositiveIntegerField()),
                ('features', models.TextField(help_text='Comma-separated features')),
                ('operating_hours', models.CharField(default='6:00 AM - 11:00 PM', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'ordering': ['zone_type'],
            },
        ),
    ]
