# Generated by Django 4.2.29 on 2026-03-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('is_featured', models.BooleanField(default=False)),
                ('color_label', models.CharField(choices=[('primary', 'Primary (Yellow-Green)'), ('secondary', 'Secondary (Cyan)'), ('tertiary', 'Tertiary (Gold)'), ('outline', 'Outline (Gray)')], default='primary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
