# Generated by Django 6.0.3 on 2026-04-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plans/'),
        ),
    ]
