# Generated by Django 4.2.29 on 2026-03-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('zone', models.CharField(choices=[('main_hall', 'Main Hall'), ('zone_b', 'Zone B'), ('yoga_room', 'Yoga Room'), ('cardio_zone', 'Cardio Zone'), ('weight_room', 'Weight Room'), ('pool', 'Pool'), ('spa', 'Spa')], default='main_hall', max_length=30)),
                ('activity', models.CharField(choices=[('general', 'General Training'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('cardio', 'Cardio Blast'), ('powerlifting', 'Powerlifting'), ('crossfit', 'CrossFit'), ('leg_day', 'Leg Day'), ('upper_body', 'Upper Body'), ('personal_training', 'Personal Training')], default='general', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_set', to='members.member')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
    ]
